### ISSUE TITLE
[Request side] add some kind of indicator to tell user to press 'enter' after each skill they need help with

### ISSUE THREAD

**Issue by celineselee** [ELozhkin/MentorApp#20]
it's not obvious that u need to press enter after each type of skill is added 

Maybe something like "Press enter after each skill you need help with" (reworded, of course) 

![image](https://user-images.githubusercontent.com/25260228/51060645-67be3900-15be-11e9-8f69-f0d10cab35b3.png)

**Comment by ELozhkin** [comment]
![image](https://user-images.githubusercontent.com/35240686/51062918-b40d7700-15c6-11e9-8074-6c4c01c1b6dc.png)
does something like this work?

**Comment by celineselee** [comment]
all good
