### ISSUE TITLE
[Request side] multiple chips aren't separated in "review request" section

### ISSUE THREAD

**Issue by celineselee** [ELozhkin/MentorApp#21]
<img width="189" alt="react_app" src="https://user-images.githubusercontent.com/25260228/51060708-a18f3f80-15be-11e9-918c-a1ece43944e6.png">

**Comment by ELozhkin** [comment]
i think the simplest way is to use the chips again - not the prettiest but makes it most clear that these are separate skills.
![image](https://user-images.githubusercontent.com/35240686/51063177-d653c480-15c7-11e9-93bb-74fbac485d35.png)

**Comment by celineselee** [comment]
yep! but these shouldnt be editable :-)

**Comment by celineselee** [comment]
also add padding between each chip (5px)
